language: go

go:
  - 1.11.x

os:
  - linux
  - osx
  - windows

gobuild_args: -x -ldflags "-X github.com/derekbekoe/convey/cmd.VersionGitCommit=$TRAVIS_COMMIT -X github.com/derekbekoe/convey/cmd.VersionGitTag=$TRAVIS_TAG"

script:
  - go test -v ./...
  - go build -v -o bin/convey

sudo: false
